branches:
  only:
  - master
  - /^.*-dev$/

language: sh
os:
  - linux
services: 
  - docker
before-install: 
  - docker pull debian:10.7
script:
  - ./.travis_scripts/travis_docker_build.sh
notifications:
  slack:
    rooms:
    - opencdi:fRj7xoMZXkFdVmlyw7h4J93t#test
  secure: "T4dzQtx6v3NC/IO4kEgl8DM38M1p/7/MgjXcIZkQa9KQs4BXQhyCukv+xVNSaYfJPf0T8iAWTOG0r1Q0SrZt6lGwYV/BNLwI5YBzm6DKHOrrBBp0J1wArnzbXVNVJj37J/EDe7hv2Mq37IFFvRSdQELe19SKM6g+eLULNSqu+eXfmQHxVr30tNqm0JisODEsjC3YrgEJdPjumcO3Oy1eBytu1JRomokJIsENZNoA2lT/wA3b0kKr9ep6pySUqn6VlTJ9VYfTE8xdPFR3EZu67vOgS0XdyF74heiMk7eOHJRRkFbf+V2vIgEqwDpSfr1aosXe4xJzsK16ACLch/cio3XdMeTfKidJYVptIps1RxCEReXLeGmlGm1fvyW9i0kBb7R12ifIvaDcJ/xtzos6iwl6XWrcSszq3ATvN4TRO/0Yd7y9UG53X/jxHxG/6j7h95Fo71VqvNwAfZ9bMZMukD6aPESAaMB8/NwX5FFd0Pw36XFX/H1LTD8Co2j/lqxo+h4w4q9NK1g10hc8nR12S/DRMXCgft1d3sQowHKkkovV53ko9weQmLOS4rXARfLaWiOf8CopRpF6OPZsBSW9CaDfT1mjzy06aQ4Si4t/zybc39d75rK4IsX6MhUniH1xjFU3sbzexhwT+UGBykf4/siGXddf+EJAT/LzIWLJqpA="
  secure: "VbdAtRbFpxN7Y10iA3qmrS9/0epx15IIAX8Xp7UlmSHQsDoYBq8P8OCZ0zunhUDK3ZMJj0L1WW/ej2VDGxlQQS5eJ2bUbeecK28kD8iO1RG4bfyMPb0A9ZtJ1l0wHy3h3JR1IMb2zf/CRNbuXI0b2N2T2agvCEljlSndFn6HE0ar9os4Kx/r8sGDMQH53tjwRqzgDlnkFguhiw4zfDmE0oUc28QT17fmusRKAcviuAw97wicqN3Y0+TWeNtzNOap7TbE0iArL7ynHo+Bk0UnIxibS6OasxIqfTiVKK0fUSnx0Z9uzvpXn763frEfacnEXoEZUFMU9ugVp1kLVCd9EVIRGZOm9NGw6UOxRWKICBjFCb/BLmyOantCV3YQQm0+EmxRMnzq8zx3sXHHT5MJVQQTHZ/GfIos1I+Rs4vO4E1SQs/4UGQRJvWKWagi2IQsN6HdGCqEqtGME+R3eyE7bYdvg6E3HewB8fVe/Teow6tnvQo7qEUFwK2nUdQw4qCLy40xMTdfiQF3hgPxoHWR4Itctgt6UrQkQRXTnfgfpVXxL47P6a63o35XsNSJrqzlsHF1PL9SRSQHAF3ToQkrR7UsXeKIAZDK6MDLvbODyTwH65/7+XJjDOw1evjp/eCpaeElY94QedUCRIaILKAYhEVXW1apSV/aUENf7Esb4Cw="

deploy:
  provider: script
  script: ./.travis_scripts/travis_docker_push.sh
  on:
    branch: master
