branches:
  only:
  - master
  - /^.*-dev$/
language: sh
os:
  - linux
services: 
  - docker
before-install: 
  - docker pull debian:10.7
script:
  - ./.travis_scripts/travis_docker_build.sh
notifications:
  slack:
    rooms:
    - opencdi:fRj7xoMZXkFdVmlyw7h4J93t#test

deploy:
  provider: script
  script: ./.travis_scripts/travis_docker_push.sh
  on:
    branches:
    - master
    - fix-travis-script
