branches:
  only:
  - master
  - fix-travis-script
  - /^.*-dev$/
language: sh
os:
  - linux
services: 
  - docker
before-install: 
  - docker pull debian:10.7
script:
  - ./.travis_scripts/travis_docker_build.sh
notifications:
  slack:
    rooms:
    - opencdi:fRj7xoMZXkFdVmlyw7h4J93t#test
deploy:
  provider: script
  script: ./.travis_scripts/travis_docker_push.sh
  on:
    branche: master
  provider: script
  script: ./.travis_scripts/travis_docker_push.sh
  on:
    branch: fix-travis-script
env:
  global:
  - secure: gKxSxDHPLVSNh/j86HP2P47FrytIhuRlOi+QZCeegilf1gemX8JWA5AdRjA2VlR2xFiW2CZsmoxRrOMXJyVMxXlRZeoGqNzvYp0Yu9bn+D2oUPV/zCQcuxGI0OmaSxfwRPElVgbXDSbtFCwWQplnsN1eoulPtUiVkdaBNrjlj/TqLI7v3Ulgz+mablfGkH3Vn3lF49fAJnq52UH0gLSTZSX4GbViVtqoXlmY8mobdeOl9c7X8HiQTg4Qg7oxDk6/AbhR95TE0WXwaKSBVS/+ToPkeUZ60DHbegtoFwKKfW8W4nP4DcCf2TOThbbRs0KG4vD2QigRhQUdOgwpaSvOhKSHela0Bw2rD1oglIuRT7c1Er6bBVDrJrP2ezWo1GsDN1/Or695LcOoN5C/WEuBVEPg6bAW2NdHMfV0TX8cHQ8w5DErAh3IAdxVBcfU7N9R2R9T7HbWTsaIUqgiz8pGpnL/IAfu5cX78FVvyEXopy+CMw0tMkt2sNSVL/zaHCg7SH2wOUIQxN0QvIkiRgKvWPdPPLY1Vz0hIgwGjjq3MchoIh/8iHHSfD+xfXHcgYqWhxIacZ1mZZj0A13yauNhb+nwGijYJuJPA2t8rI6E98p0kV2IZbY+sw591TxqN5+TgK/S1a5bKXNtJHAmU1u0xD/peA+wXbV70qwVmHRbTt8=
  - secure: ODwMWhpxS9zvLPSU+gJ9SXN6Co/FyAn6dSirmZsMOdcTk84Yq+t3RiT1rEC33Dt+obapyNcFvUwZMnNiBwCyijOlsn3ay6bKjrkIColn3YfwHDYIMB9aMgTWiBmjVVvG59E05oM6qjkFwXts1GZjbAIOHh5XQkpR5/SrzUvS2RlU2Cp39YotD8iiEZ/coZ9OvGwOIMuBGnAdiDr+9DGoGFPW75vS6njpxGmMEZa5eEQo6JOi76sTw5f3Ysh4KP0Ff3O0JYcaYzYawwV34dIGfhSGLpSoIpvWsrL1zHX6dxtXz5O5tSeYoSZhn1tcYPuW8bAdgV+ZGBkBavbrI7GwBZACkjvVLE4ovU4+nsGFawpRFBaVrOW0YkF89cXyGQXOACGpYYmKnIR8aU9COCvtouTwrleYb5WvR4EjveMj+eli1BvTEao/Lsz9qUxyt5j631i9qUhrACg30zhmvxtD9sAs0dO8iV3FT1z8r8qEGLebwKWmN1kyc5PgI9u6H2mTWMxTq6SG8IAGvBDglvTrL7joEVa/ICvPk6nk1bQRIiV0CxmnvLrqUoykQEz33KlorrOXkSVDxHuTk5NYT3+mHC8jwppDozlUrSoTyc4Lq8VKHYQ/vVEopBlk34lPQzxQsqIpwCHi7Im5mjIo5Yrkn/hkQ7Cx6db4JcrVTn+cKTY=


