name: build-and-push-images

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  LOGIN_NAME: coshapp

jobs:

  # Push image to DockerHub.
  # See also https://docs.docker.com/docker-hub/builds/
  push-production:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username okadash --password-stdin

      - name: Build and push Debian Base images
        run: |
          . .github_script.sh
          build_image Debian-Base/Core_*
          push_image Debian-Base/Core_*
          build_image Debian-Base/*
          push_image Debian-Base/*
          rmi_without_core
          build_image Debian-Dev/*
          push_image Debian-Dev/*
          rmi_without_core
          build_image Debian-System/*
          push_image Debian-System/*
