name: deb-testimg

on:
  push:
    # Publish `test`, `*-test` branch as *-test image.
    branches:
      - test
      - '**-test'

env:
  LOGIN_NAME: coshapp

jobs:

  # Push image to DockerHub.
  # See also https://docs.docker.com/docker-hub/builds/
  push-test-img:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username okadash --password-stdin

      - name: Build and push Debian-based test images
        run: |
          . .github_script.sh
          set_test_target
          filtered_build
          filtered_push
