name: debian-base

on:
  schedule:
    - cron: '3 20 * * 6'

env:
  LOGIN_NAME: coshapp

jobs:

  # Push image to DockerHub.
  rolling-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username okadash --password-stdin

      - name: Build and push Debian Base images
        run: |
          . .github_script.sh
          build_image Debian-Base/*
          build_image Debian-Dev/*
          build_image Debian-System/*
          push_image Debian-Base/*
          push_image Debian-Dev/*
          push_image Debian-System/*
