name: debian-base

on:
  push:
    # Publish `test` or `*-dev` branch as *-test image.
    branches:
      - test
      - '**-dev'

env:
  LOGIN_NAME: coshapp

jobs:

  # Push image to DockerHub.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username okadash --password-stdin

      - name: Build and push Debian Base images
        run: |
          . .github_script.sh
          [ "${GITHUB_REF}" != "${GITHUB_REF%-dev}" ] && target="$(echo ${GITHUB_REF%-dev} )"
          TAG_POSTFIX="test" filtered_build
          TAG_POSTFIX="test" filtered_push
