name: test-scripts

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - dev
  pull_request:
    branches:
      - master

env:
  REGISTRY_NAME: coshapp

jobs:

  # Push image to DockerHub.
  # See also https://docs.docker.com/docker-hub/builds/
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Debian Base images
        run: |
          bash -c ". ci_functions.sh; set_test_target 'firefox'; test_build; test_push "
